### ISSUE TITLE
ERD/Database modell

### ISSUE THREAD

**Issue by MrBrown95** [nikderoso/TIT#12]
Entity-Relationship-Modell erstellen

**Comment by Marcel-1999** [comment]
eine weitere Tabelle für "Flags" hinzufügen

**Comment by Marcel-1999** [comment]
Entity (Tabelle) "Flags" mit relations hinzugefügt

**Comment by Marcel-1999** [comment]
komplette Neustrukturierung des Entity-Relationship-Diagramm

**Comment by Rethox** [comment]
![SSAS_Überblick_0](https://user-images.githubusercontent.com/56953353/67562901-e801f500-f71f-11e9-8161-fcda176a8f5c.JPG)

**Comment by Marcel-1999** [comment]
fertigstellung des ERD

**Comment by Marcel-1999** [comment]
![ERD](https://user-images.githubusercontent.com/55581226/67564803-1d104680-f724-11e9-8c76-b6f2d44741fb.PNG)

**Comment by bjarnet** [comment]
reopened because of changes of the database structure

**Comment by bjarnet** [comment]
![grafik](https://user-images.githubusercontent.com/55580718/72058760-f0a2aa00-32d0-11ea-8cc7-7f62aa4e0781.png)

**Comment by niclas-juelke** [comment]
[database_modell.zip](https://github.com/nikderoso/TIT/files/4235733/database_modell.zip)
![DataBaseModell](https://user-images.githubusercontent.com/56953295/75029848-2d062000-54a3-11ea-82ba-b0d6098767f4.JPG)
