### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by TheKillerPepsi** [nikderoso/TIT#17]
This is an issue for adding images to the wiki.

**Comment by TheKillerPepsi** [comment]
![Testpic](https://user-images.githubusercontent.com/44766164/67549450-91d38880-f704-11e9-8199-98fbc6658cd0.JPG)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67550063-e88d9200-f705-11e9-9711-013ae5d29497.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67550160-1541a980-f706-11e9-9b43-71210152a0dd.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67550228-3b674980-f706-11e9-9c8f-72fbe34c7847.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67550331-7ec1b800-f706-11e9-9dbb-1891b2226217.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67550357-9305b500-f706-11e9-99bb-30e056a6096f.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67557890-37432800-f716-11e9-86aa-6623a389ba27.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67558543-78880780-f717-11e9-9d2a-b7ae4f822475.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67558800-f815d680-f717-11e9-9fbb-e21070169065.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67558971-475c0700-f718-11e9-93a5-900db947819e.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67559486-598a7500-f719-11e9-9f08-dd0b7433a05a.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/67562527-25b24e00-f71f-11e9-91c6-54b7356949ca.png)

**Comment by Jehlen** [comment]
![WhatsApp Image 2019-11-15 at 11 28 23](https://user-images.githubusercontent.com/56953065/68937792-5b39dc80-079d-11ea-8d89-fb21f08b5884.jpeg)
![WhatsApp Image 2019-11-15 at 11 26 32](https://user-images.githubusercontent.com/56953065/68937797-5d9c3680-079d-11ea-972e-404ac4c8550b.jpeg)

**Comment by Trenos** [comment]
[database_modell.pdf](https://github.com/nikderoso/TIT/files/3851179/database_modell.pdf)

**Comment by Trenos** [comment]
![database_erd](https://user-images.githubusercontent.com/56919171/68939402-d486fe80-07a0-11ea-8675-0cfdc7d14306.png)

**Comment by Trenos** [comment]
![database_modell](https://user-images.githubusercontent.com/56919171/68939417-dc46a300-07a0-11ea-9298-4b492a38e30e.png)

**Comment by Trenos** [comment]
[database_modell.pdf](https://github.com/nikderoso/TIT/files/3851228/database_modell.pdf)

**Comment by Tillow** [comment]
![Tit Expanded](https://user-images.githubusercontent.com/37675923/72143335-d59a6d80-3396-11ea-84c3-70f8fb9856ee.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/72144967-c8cb4900-3399-11ea-8660-f2f76e11ce4f.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/74712657-1b184900-5227-11ea-9ed0-51d58c1e6e0a.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/76293366-32d86f80-62b1-11ea-89ca-4bf068d28ae9.png)

**Comment by Anette-16** [comment]
![grafik](https://user-images.githubusercontent.com/55580129/76293411-42f04f00-62b1-11ea-832c-1b5a07080ece.png)
