### ISSUE TITLE
Informationsbeschaffung SSAS und R Prozesse

### ISSUE THREAD

**Issue by Marcel-1999** [nikderoso/TIT#21]
Als Zwischenaufgabe: Beschaffung erster Informationen über SSAS Prozesse und R Prozesse
--
Stand 27.01.2020:

Anforderungen R:

-Füllen von Lücken in den Wetterdaten
	-räumlich
	-zeitlich

-Valdieren von Daten (Homogenisieren)
	-Ausnehmen von unrealistischen/sehr abweichenden Ergebnissen
		-> ersetzen durch berechnete Ergebnisse

-Analyse der Wetterdaten
	-> komplexer als MIN/MAX ??

-

**Comment by Rethox** [comment]
SSAS Überblick

![SSAS_Überblick_0](https://user-images.githubusercontent.com/56953353/67563039-344d3500-f720-11e9-802c-22ce4797214c.JPG)

**Comment by Rethox** [comment]
### Verwendung von SSAS 
Auf Basis eines bestehenden Data Warehouses (DWH), welches bereits mithilfe von ETL-Prozessen mit Ausgangsdaten aus den Quellsystemen befüllt wurde (beispielsweise mittels Microsoft SQL Server Integration Services, SSIS), kann mithilfe von SSAS eine Analyse dieser Daten erfolgen. Dabei kann es sich zum Beispiel um die Erzeugung von OLAP-Cubes (Ein OLAP-Würfel oder Datenwürfel (englisch OLAP cube oder engl. data cube), auch Cube-Operator genannt, ist ein in der Data-Warehouse-Theorie gebräuchlicher Begriff zur logischen Darstellung von Daten.) oder auch die Generierung von Reports handeln.
Die Daten im Data Warehouse können zudem in einem Zwischenschritt zuvor segmentiert werden, um extra für bestimmte Geschäftsbereiche oder Analysezwecke erzeugte Data Marts bereitzustellen.
