### ISSUE TITLE
Convert csv-daten from meteostat-raw

### ISSUE THREAD

**Issue by Trenos** [nikderoso/TIT#25]
using the synop raw data if possible, when there is no synop-data then using the metar-data
-----
the raw data cannot be collected through the api

- [x] needed to contact meteostat again because of the weather condition
--
- [x] collect .csv-files
- [x] check stations from synop and metar
--
- [x] build script
- [x] test script
- [x] convert files (synop)
- [x] convert files (metar)
--
- [x] import raw files to temp-tables sql-server
- [x] insert and convert data into live-table
->Add bit-column with value 1
->Replaces '' with NULL
->insert_select-script
--
- [x] replace station number and weather condition code with id from foreign table
- [x] create backup
- [x] test backup

**Comment by bjarnet** [comment]
no match for STATION_NUMBER_TEMP
91218
91221
78224
91233
91366 AND

NULL AND '' FOR WTH_CODE_NUM_TMP

->
