### ISSUE TITLE
Cube erstellen

### ISSUE THREAD

**Issue by bjarnet** [nikderoso/TIT#46]
https://docs.microsoft.com/de-de/sql/analysis-services/lesson-2-defining-and-deploying-a-cube?view=sql-server-2014

**Comment by bjarnet** [comment]
Installed SQL Server Data Tools on s-msssql2019.

**Comment by Rethox** [comment]
Test 2-Dimensionalen Cube auf Datenbank IN18 Aufgesetzt. Measures definiert und Berechnung getestet.
