### ISSUE TITLE
Logo Erstellung

### ISSUE THREAD

**Issue by niclas-juelke** [nikderoso/TIT#55]
Erstellen eines Logos.

**Comment by niclas-juelke** [comment]
![LogoMinimal 2](https://user-images.githubusercontent.com/56953295/81379794-0488dc00-910a-11ea-9c3b-185aa6eef0ed.jpg)

**Comment by niclas-juelke** [comment]
![logo_white_large](https://user-images.githubusercontent.com/56953295/81380456-3ea6ad80-910b-11ea-9c23-3620b77a7443.png)
![LogoMinimal_2-removebg-preview](https://user-images.githubusercontent.com/56953295/81380477-46fee880-910b-11ea-8fbb-1f73f3728641.png)

**Comment by niclas-juelke** [comment]
![logo_large](https://user-images.githubusercontent.com/56953295/81385901-6ea67e80-9114-11ea-8ce9-9ae6ffc8cf50.png)
![logo_small](https://user-images.githubusercontent.com/56953295/81385904-6f3f1500-9114-11ea-8e0f-3fde0e1310bc.png)
![logo_white_large](https://user-images.githubusercontent.com/56953295/81385907-6f3f1500-9114-11ea-9608-bd09caac1072.png)

**Comment by niclas-juelke** [comment]
![logo_large](https://user-images.githubusercontent.com/56953295/81388459-9d265880-9118-11ea-9693-8dced9f963bb.png)

**Comment by Balyndir** [comment]
![Logo](https://user-images.githubusercontent.com/55580100/81389262-d57a6680-9119-11ea-9845-cbc5529e00d9.jpg)

**Comment by Balyndir** [comment]
![Logo_2](https://user-images.githubusercontent.com/55580100/81389280-db704780-9119-11ea-82cc-e48b386f1404.jpg)

**Comment by Balyndir** [comment]
![Logo_3](https://user-images.githubusercontent.com/55580100/81389289-df9c6500-9119-11ea-8945-34cce9a4638e.jpg)

**Comment by Balyndir** [comment]
![Logo_4](https://user-images.githubusercontent.com/55580100/81389299-e3c88280-9119-11ea-8498-cb5c38bd2fe2.jpg)

**Comment by niclas-juelke** [comment]
![logo_large](https://user-images.githubusercontent.com/56953295/81390074-263e8f00-911b-11ea-91f3-59397007c49d.png)
![logo_small](https://user-images.githubusercontent.com/56953295/81390075-26d72580-911b-11ea-8519-9a35d7d5661e.png)
![logo_small_icon_only](https://user-images.githubusercontent.com/56953295/81390077-276fbc00-911b-11ea-8c4e-a95abaabd1f4.png)
![logo_small_icon_only_inverted](https://user-images.githubusercontent.com/56953295/81390078-276fbc00-911b-11ea-9317-22aa56ddb4aa.png)
![logo_white_large](https://user-images.githubusercontent.com/56953295/81390079-276fbc00-911b-11ea-99d9-ff4be82f6ee2.png)

**Comment by niclas-juelke** [comment]
Eine Umfrage hat ergeben, das dieses Logo in die Website integriert werden soll.
![81380477-46fee880-910b-11ea-8fbb-1f73f3728641 (1)](https://user-images.githubusercontent.com/56953295/81396279-64d94700-9125-11ea-8fa2-a9bf3fd3ac4c.png)
